import localFont from "next/font/local";
import "../globals.css";
import { Logo } from "../../../public/icons/logo";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Contact Pro - Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-96 mx-auto`}
      >
        <main className="bg-colorBg px-4 min-h-screen">
          <header className="py-20 space-y-1">
            <div className="w-fit mx-auto">
              {
                Logo()
              }

            </div>

            <h2 className="text-accent font-bold text-center">CONTACT PRO</h2>
          </header>

          {children}

          <Toaster
            position="top-right"
            reverseOrder={false}
          />
        </main>
      </body>
    </html>
  );
}
